[tool.statisfactory]
project_slug = "exemple"
configuration = "conf"
catalog = "conf/catalog.yaml"
sources = "Lib"
notebook_target = "__compiled__"
pipelines_definitions = "Pipelines/definitions/pipelines.yaml"
parameters = "Pipelines/configurations/pipelines.yaml"