name: Tests suite

on: [push, pull_request]

jobs:
 testing:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      python-version: [3.8, 3.9]

  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
        virtualenvs-in-project: false
        installer-parallel: true

    - name: Run tox tests
      run: tox
    
    - name: Upload Codecov Results
      if: success()
      uses: codecov/codecov-action@v1
      with:
        file: coverage.xml
        flags: unittests
        name: coverage-${{ matrix.python-version }}
        fail_ci_if_error: false
    
